// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "azure_authentication" {
  type = object({
    client_id       = string
    client_secret   = string
    subscription_id = string
    tenant_id       = string
  })
}
variable "azure_storage_account_data_lake" {
  type = object({
    data = object({
      infrastructure = object({
        ari      = string
        endpoint = string
      })
      security = object({
        iam = optional(map(object({
          role  = any
          scope = string
        })))
      })
    })
    specs = object({
      azure = optional(object({
        region = string
      }))
    })
  })
}
variable "database" {
  type = object({
    allowed_origins = string
    region          = string
  })
}
variable "logging" {
  type = object({
    enable_logging = bool
  })
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "monitoring" {
  type = object({
    mode = optional(string)
    alarms = optional(object({
      availability_metric_alert = optional(object({
        aggregation = string
        frequency   = string
        operator    = string
        severity    = number
        threshold   = number
        window_size = string
      }))
      total_errors_metric_alert = optional(object({
        aggregation = string
        frequency   = string
        operator    = string
        severity    = number
        threshold   = number
        window_size = string
      }))
      total_latency_metric_alert = optional(object({
        aggregation = string
        frequency   = string
        operator    = string
        severity    = number
        threshold   = number
        window_size = string
      }))
    }))
  })
}
variable "registry" {
  type = list(object({
    image_name   = optional(string)
    login_server = optional(string)
  }))
}
